fix FTBS on i386/i686: int size mismatch
build breaks due integer size mismatch:

> ../../src/dummy_driver.c: In function 'dummy_output_mode_set':
> ../../src/dummy_driver.c:246:17: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
>   246 |     int index = (int64_t)output->driver_private;
>       |                 ^
> ../../src/dummy_driver.c: In function 'dummy_output_detect':
> ../../src/dummy_driver.c:258:17: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
>   258 |     int index = (int64_t)output->driver_private;
>       |                 ^

Need to use uintptr_t instead of plain int.

Signed-off-by: Enrico Weigelt, metux IT consult <info@metux.net>
Part-of: <https://gitlab.freedesktop.org/xorg/driver/xf86-video-dummy/-/merge_requests/13>